print("(A):")
list=[3, 1, 4, 1, 5, 9, 2, 6, 5]
list.append(8)
list.extend([1,0,1])
list.remove(3)
list.reverse()
print(list)
print("Ascending Order:",sorted(list))
print("Descending Order:",sorted(list,reverse=True))
print("\n(B)")
list1=[1,2,3,4]
list1.extend([ ["python", "java", "c++", [10,20,30]]])
list1.extend([5,6,7])
list1.extend([ ["apple", "banana", "orange"]])
print("Word 'orange':", list1[8][0])
print("Word 'Python':", list1[4][0])
print("Repeated List (5 times):", list1*5)
print("\n(C)")
list2 = [10, 20, 30, 40, 50]
list3 = list2[:]
print(list2)
print(list3)
my_tuple = (5, 8, 3, 1, 7, 2)
sum_tuple = sum(my_tuple)
max_tuple = max(my_tuple)
min_tuple = min(my_tuple)
print("\n(D)")
print("Tuple:", my_tuple)
print("Sum of Tuple:", sum_tuple)
print("Maximum of Tuple:", max_tuple)
print("Minimum of Tuple:", min_tuple)
print("\nThis Program is Prepared by 22CE103 Bhavya")